<?php

/**
 *
 */

/**
 *
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function recent_form_alter(&$form, $form_state, $form_id) {
  // content type edit
  if ($form_id == "node_type_form") {

    // Create a fieldset that will be included in the vertical tab.
    $form['recent'] = array(
      '#type' => 'fieldset',
      '#title' => t('Recent'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#tree' => TRUE,
      // Send this tab to the top of the list.
      '#weight' => -99,
      '#group' => 'additional_settings',
    );

    $form['recent']['enabled'] = array(
      '#type' => 'checkbox',
      '#title' => t('Include in recents'),
      '#default_value' => variable_get('recent_' . $form['#node_type']->type, FALSE),
    );

    $form['#submit'][] = 'recent_node_type_form_submit';
  }
}

function recent_node_type_form_submit($form, &$form_state) {

    variable_set('recent_' . $form['#node_type']->type, $form_state['values']['recent']['enabled']);

}


// write records to new table when a node is viewed


function recent_node_view($node, $view_mode) {

  $isTrackable = variable_get('recent_' . $node->type, FALSE);
  if ($isTrackable && $view_mode == 'full') {
    global $user;
    if ($user->uid != 0 && $node->nid != 0) {
      $record = new stdClass();
      $record->user_id = $user->uid;
      $record->node_id = $node->nid;
      $record->timestamp = strtotime('now');
      drupal_write_record('node_views', $record);
    }
  }
}

// show recently viewed nodes titles within a block

function recent_block_info() {
  $blocks['my-block-id'] = array(
    'info' => t('Recently viewed'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function recent_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'my-block-id':
      $block['subject'] = t('Recently viewed');
      $block['content'] = recent_contents();
      break;
  }
  return $block;
}

/**
 * custom html block
 * @return string
 */
function recent_contents() {
  global $user;
  
  $result = db_query('
    SELECT node_id, max(timestamp) as most_recent
    FROM {node_views}
    WHERE user_id = :uid
    GROUP BY node_id
    ORDER BY most_recent
    DESC LIMIT 6',
    array(':uid' => $user->uid));
 

  $output = '';
  $i = -1;
  $links = array();
  global $base_url;
  
  foreach ($result as $record) {
    $i++;
	if ($i == 0) {
      continue;
    }
    $node = node_load($record->node_id);

	$links[$i-1] = array( 'title'=> $node->title,'href' => $base_url.'/node/'.$node->nid);

  }

   $rendered_HTML = theme('links', array('links' => $links), array());

  return $rendered_HTML;
}

